baseURL = "http://example.org/"
languageCode = "fr"
title = "Test for reporting gohugo.io bug "

# Build robots.txt file
enableRobotsTXT = true
enableGitInfo = true
pygmentsCodeFences = true
defaultContentLanguageInSubdir = false
defaultContentLanguage = "fr"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
    [params.agenda]
        id      = "params.agenda.id ROOT"
        title   = "params.agenda.title ROOT"
    [params.global]
        robots = "index,follow"
        [params.global.agenda]
            id      = "params.global.agenda.id ROOT"
            title   = "params.global.agenda.title ROOT"
    [[params.listeLangues]]
        code = "fr"
    [[params.listeLangues]]
        code = "en"

[languages]
    [languages.fr]
        languageCode = "fr-fr"
        title = "languages.fr.title"
    [languages.fr.params.agenda]
        enable  = true
        id      = "languages.fr.params.agenda.id FRANCAIS"
        # title   = "languages.fr.params.agenda.title FRANCAIS"

    ## If you remove this section global you get [params.global.agenda] values
    ## if you COMMENT id from this section you get empty values for id instead of ROOT value
    # [languages.fr.global]
    #    [languages.fr.global.agenda]
    #        # id      = "languages.en.params.global.agenda.id FRANCAIS"
    #        title   = "languages.en.params.global.agenda.title FRANCAIS"

    [languages.en]
        languageCode = "en"
        title = "languages.en.title"
    [languages.en.params.agenda]
        enable  = true
        # id      = "languages.en.params.agenda.id ENGLISH"
        title   = "languages.en.params.agenda.title ENGLISH"

    [languages.en.params.global]
        [languages.en.params.global.agenda]
            id      = "languages.en.params.global.agenda.id ENGLISH"
            title   = "languages.en.params.global.agenda.title ENGLISH"
