# baseURL non nécessaire pour consultation directe en filesystem.
baseURL = "http://10.0.100.152:8000/"
# Nécessaire pour consultaion directe en filesystem
relativeURLs = true
uglyURLs = true
# Fin des options pour usage file system
# Option pour usage WebServer
# canonifyurls = true

languageCode = "fr"
DefaultContentLanguage = "fr"

title = "Stats"
theme = "uno-master-v2"

disableFastRender = true
cleanDestinationDir = true

contentdir = "content"
# publishdir = "../public"
builddrafts = false
author = "DG"
copyright = "Utilise Hugo + https://github.com/chartjs/Chart.js"

disableKinds = ["taxonomy","taxonomyTerm","RSS"]

timeout=30000

[outputs]
home = [ "HTML"]

[params]
  version_stats = "0.3.5"
  description = "Test for hugo 0.55"
  cover = "/images/background-cover.jpg"
  logo = "/images/logo-stats.png"

  dateFormat = "02/01/2006"

  # Pour éviter de traiter les gros fichiers CSV pendant le développement.
  # modeDev = true
  modeDev = false
