baseURL = "http://example.org/"
languageCode = "fr"
title = "Test for reporting gohugo.io bug "

# Build robots.txt file
enableRobotsTXT = true
enableGitInfo = true
pygmentsCodeFences = true
defaultContentLanguageInSubdir = false
defaultContentLanguage = "fr"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
    [params.case_1_lang]
        id      = "params.case_1_lang.id ROOT"
        title   = "params.case_1_lang.title ROOT"

    [params.case_problem]
        id      = "params.case_problem.id ROOT"
        title   = "params.case_problem.title ROOT"

    [params.case_3_nolang]
        id      = "params.case_3_nolang.id ROOT"
        title   = "params.case_3_nolang.title ROOT"

    [[params.listeLangues]]
        code = "fr"
    [[params.listeLangues]]
        code = "en"

[languages]
    [languages.fr]
        languageCode = "fr-fr"
        title = "languages.fr.title"

        [languages.fr.params.case_1_lang]
            id      = "languages.fr.params.case_1_lang.id FRANCAIS"
            title   = "languages.fr.params.case_1_lang.title FRANCAIS"
        [languages.fr.params.case_problem]
            # id      = "languages.fr.params.case_problem.id FRANCAIS"
            title   = "languages.fr.params.case_problem.title FRANCAIS"

    [languages.en]
        languageCode = "en"
        title = "languages.en.title"

        [languages.en.params.case_1_lang]
            id      = "languages.en.params.case_1_lang.id FRANCAIS"
            title   = "languages.en.params.case_1_lang.title FRANCAIS"
        [languages.en.params.case_problem]
            # id      = "languages.en.params.case_problem.id FRANCAIS"
            title   = "languages.en.params.case_problem.title FRANCAIS"
